var excipio_xml = (function (my_module) {

    function getIssueDetailsXML(details) {
        var xml_string = '';
        details.forEach(function(detail, index) {
            xml_string += '\n\t\t\t\t\t<IssueDetail';
            Object.keys(detail).forEach(function(key, key_index, keys) {
                xml_string += (' ' + key + '="' + detail[key] + '"');
            });
            xml_string += '/>';
        });
        return xml_string;
    }

    function getIssuesXML(issues) {
        var xml_string = '';
        issues.forEach(function(issue, index) {
            xml_string += '\n\t\t\t<Issue';
            Object.keys(issue).forEach(function(key, key_index, keys) {
                if(!Array.isArray(issue[key])) {
                    xml_string += (' ' + key + '="' + issue[key] + '"');
                }
            });
            xml_string += '>';

            xml_string += '\n\t\t\t\t<IssueDetailList keys="issue_detail">';
            xml_string += getIssueDetailsXML(issue.issue_details);
            xml_string += '\n\t\t\t\t</IssueDetailList>';

            xml_string += '\n\t\t\t</Issue>';
        });
        return xml_string;
    }

    function getAddressXML(address) {
        var xml_string = '';
        xml_string += '\n\t\t\t<Address';
        Object.keys(address).forEach(function(key, key_index, keys) {
            if(!Array.isArray(address[key])) {
                xml_string += (' ' + key + '="' + address[key] + '"');
            }
        });
        xml_string += '/>';
        return xml_string;
    }

    function getCaseRecordXML(visit) {
        var xml_string = "\n\t<Case";
        Object.keys(visit).forEach(function(key, index, keys) {
            if(!Array.isArray(visit[key]) && key != '_id' && key != 'address' && key != 'issues') {
                xml_string += (' ' + key + '="' + visit[key] + '"');
            }
        });
        xml_string += ">";

        xml_string += '\n\t\t<IssueList keys="issue_seq">';
        xml_string += getIssuesXML(visit.issues);
        xml_string += '\n\t\t</IssueList>';

        xml_string += '\n\t\t<AddressList keys="address_id">';
        xml_string += getAddressXML(visit.address);
        xml_string += '\n\t\t</AddressList>';

        xml_string += "\n\t</Case>";

        return xml_string
    }

    return {
        getCaseRecordXML : getCaseRecordXML
    };
}(excipio_xml));

/*
<?xml version="1.0"?>
    <CaseList>
        <Case company_id="[auto generated]" case_id="[auto generated]" initial_user_code="[user id of valid Excipio user]" responsible_user_code="[user id of valid Excipio user]"
        address_id="[0 for new address or valid address id already in the system]"
        case_status="O=Open or C=Close" case_status_code="" received="" contact_multiplier="??? Not sure if needed" b05_code="" b06_code="" b08_code="" b09_code="" b17_code="" b11_code=""
        b13_code="" b10_code="" b19_code="" case_address_role="" b21_code="" b49_code="" b17_code="[GUID generated by mobile app]">
            <IssueList keys="issue_seq">
                <Issue product_code="[SC Response]" assigned_to_user_code="[user id of valid Excipio user]" issue_status="O" issue_multiplier="1" c05_code="IP AVAIL WHR BY"
                c52_code="" c73_code="" c82_code="" custom_date1="NOT SURE what this is" c26_code="" c46_code="" c51_code="" c53_code="" c75_code="" c71_code=""
                c68_code="" c41_code="" c43_code="" c31_code=""c05_code="" c22_code="" >
                    <IssueDetailList keys="issue_detail">
                        <IssueDetail t01_code="" t03_code="" t05_code="" t06_code="" t07_code="" t08_code="" t09_code="" t10_code="" t11_code="" t12_code="" t02_code=""/>
                    .. any other IssueDetail needed…
                    </IssueDetailList>
                </Issue>
            .. any other issue needed …
            </IssueList>
            <AddressList keys="address_id">
                <Address company_id="SYS" address_id="[0 for new address or valid address id already in the system]" address_type_code="CONSUMER" active="Y" given_names="Alice" last_name="Hall" address1="23 S R 41"
                city="Burlington" state="CO " postal_code="80807" country="USA" originated_via="1" originated_date="08/21/2013 13:07:02"
                allow_survey="Y" last_contact="08/21/2013 13:07:02" accumulated_goodwill="0.00" latitude="39.3072"
                longitude="102.2665" county="Kit Carson" language_id="en" >
                    <PhoneList keys="address_phone_seq">
                        <Phone address_phone_seq="1" phone_type_code="Home" phone="719-555-1111" is_primary="N"/>
                        <Phone address_phone_seq="2" phone_type_code="Work" phone="719-555-2222" is_primary="N"/>
                        <Phone address_phone_seq="3" phone_type_code="Cell" phone="719-555-3333" is_primary="Y"/>
                    … any other phone needed
                    </PhoneList>
                </Address>
            </AddressList>
        </Case>
        <Case>……</Case>
    … and more case elements as needed
    </CaseList>
*/

exports.getCaseRecordXML = excipio_xml.getCaseRecordXML;