
module.exports = [
    {short:"  ",    culture_name:"Please select a language"},
    {short:"ar",    culture_name:"Arabic"},
    {short:"cn",    culture_name:"Chinese"},
    {short:"cz",    culture_name:"Czech"},
    {short:"da",    culture_name:"Danish"},
    {short:"de",    culture_name:"German"},
    {short:"el",    culture_name:"Greek"},
    {short:"en",    culture_name:"English"},
    {short:"en-uk", culture_name:"English UK"},
    {short:"es",    culture_name:"Spanish"},
    {short:"fa",    culture_name:"Persian"},
    {short:"fi",    culture_name:"Finnish"},
    {short:"fr",    culture_name:"French"},
    {short:"hu",    culture_name:"Hungarian"},
    {short:"id",    culture_name:"Bahasa Indonesia"},
    {short:"it",    culture_name:"Italian"},
    {short:"jp",    culture_name:"Japanese"},
    {short:"kk",    culture_name:"Kazakh"},
    {short:"lt",    culture_name:"Lithuanian"},
    {short:"lv",    culture_name:"Latvian"},
    {short:"ms",    culture_name:"Malay"},
    {short:"nl",    culture_name:"Dutch"},
    {short:"no",    culture_name:"Norwegian"},
    {short:"pl",    culture_name:"Polish"},
    {short:"pt",    culture_name:"Portugese"},
    {short:"rm",    culture_name:"Romansh"},
    {short:"ro",    culture_name:"Romanian"},
    {short:"ru",    culture_name:"Russian"},
    {short:"sc",    culture_name:"Simplified Chinese"},
    {short:"se",    culture_name:"Swedish"},
    {short:"sk" ,   culture_name:"Slovak"},
    {short:"ta" ,   culture_name:"Tamil"},
    {short:"th" ,   culture_name:"Thai"},
    {short:"tr" ,   culture_name:"Turkish"},
    {short:"uk" ,   culture_name:"Ukranian"},
    {short:"vn" ,   culture_name:"Vietnamese"}
]
